[package]
name = "loadbalancer"
version = "0.1.0"
authors = ["Magnus Hallin <mhallin@fastmail.com>"]
license = "MIT"
description = "TCP load balancer"

[dependencies]
clippy = {version = "0.0.22", optional = true}
mio = "0.6.7"
clap = "1.4"
log = "0.3"
env_logger = "0.3"
slab = "0.1"
toml = "0.1"
rustc-serialize = "0.3"

[features]
default = []
dev = ["clippy"]
